### ISSUE TITLE
3주차 회고

### ISSUE THREAD

**Issue by heozeop** [chap95/TS_study#10]
1. 좋았던 점
    1. 타입스크립트의 모듈 파일에 대해서 조금 더 자세하게 알 수 있던 것 같습니다.
    2. 시간 정해서 문제만 풀고, 바로바로 진행하니 뭔가 속도감이 있었습니다.
2. 아쉬웠던 점
    1. 딱 문제에 대해서만 설명 하니, 어떤 개념인지 정확히 파악이 어려웠던 것 같습니다.
    1. 모듈과 네임스페이스 선언에 관련하여 제대로 차이점을 구분하지 못했습니다. 앞으로는 비교하는 방식으로도 공부 해야겠다고 생각했습니다.
3. 다음에 해보면 좋을 것
    1. 개념 정리한 문서도 공유하면 좋을 것 같습니다.

**Comment by chap95** [comment]
1. 평소 몰랐던 declare 에 관한 부분을 공부 할 수 있어서 좋았다. 가려운 부분을 긁어준 느낌이랄까...
하지만 아직은 감이 잡히지 않는다. declare 를 직접 써보지 않아서 생기는 문제라 생각한다. 그래서 조만간 d.ts 를 직접 만들어 봐야겠담
2. 다음 번 스터디에서는 JS 기본에 관한 것을 하면 좋을 것 같다.

**Comment by luceinaltis** [comment]
좋은점 :다양한 부분을 탐색할 수 있어서 좋았습니다
개선할 점: 타입스크립트의 범위를 조금 벗어나서 다뤄도 좋을것 같습니다

**Comment by chap95** [comment]
3주차 회고 종료
