### ISSUE TITLE
4주차 - crispy

### ISSUE THREAD

**Issue by heozeop** [chap95/TS_study#13]
1. 다음 코드를 실행할 경우, console에 출력된 오브젝트가 가지는 속성을 말해주세요. 기준은 chrome입니다.
  ```typescript
    function doSomething(){}
    doSomething.prototype.foo = "bar";
    console.log( doSomething.prototype );
  ```

1. 프로토타입의 속성 검사를 hasOwnProperty로 하게됩니다. 일반 속성 접근과의 차이를 설명해 주세요.

1. 프로토타입의 상속 방법 3가지를 작성해 주세요.

**Comment by chap95** [comment]
1. { foo: 'bar' }
2. hasOwnProperty 는 생성자의 Prototype 으로 접근하고 일반 속성 접근은 객체.__proto__ 로 접근을 한다.
3.  - 생성자함수 , - 객체 리터럴 , - Object() 생성자 (?)
