### ISSUE TITLE
2주차 회고

### ISSUE THREAD

**Issue by heozeop** [chap95/TS_study#5]
#  생긴 질문
1. 컴파일러 옵션에서 types의 활용
2. base dir 과 rootdir의 차이
3. module과 module resolution, target의 차이

# 좋았던 점
1. 몰랐던 옵션들을 몇가지 알게되었다.
2. 내가 설명이 안되는 상황을 몇가지 만났다.

# 아쉬운 점
1. 깃허브에서 보이는 md가 별로 안이쁘다는 걸 생각하지 못했다.
2. 설명할 때, 정확히 스토리 정리를 하지 않아 매끄럽지 못했습니다.
3. 문제의 의도를 전달하기 어려웠습니다.

# 다음에 했으면 좋겠는 점
1. 의도를 문제 상단에 적어 놓으면 좋을 것 같습니다.

**Comment by luceinaltis** [comment]
좋았던 점
- 상황을 가정하여 접근한 문제 방식이 좋았습니다.

안좋았던 점
- config에 대한 내용이라 토론할 만한게 없어서 아쉬웠습니다

생긴 질문
- baseUrl의 정확한 의미

**Comment by chap95** [comment]
2회차 회고 종료
