### ISSUE TITLE
3주차_하준혁

### ISSUE THREAD

**Issue by chap95** [chap95/TS_study#8]
# 3주차 문제    
- 다음 예제코드를 본 후 물음에 답하시오.
```
declare module '*.gif' {
  const content: StaticImageData

  export default content
}
```

#### 2. 위 예제 코드와 아래에 나온 코드의 차이점을 말해주세요.
```
declare namespace gif {
  const content: StaticImageData
  
  export default content
}
```

#### 3. 타입스크립트의 namespace 는 JS 의 어떠한 문제를 해결하기 위해 만들어졌나요?

**Comment by heozeop** [comment]
1.
gif 형식의 파일 타입을 선언합니다.
이 모듈은 content라는 이름의 변수를 가지고 있습니다.
이 모듈을 통해 content라는 변수에 접근이 가능합니다.

2.
모르겠습니다 ㅎㅎ...

3.
이름 충돌을 방지하기 위해 만들어 졌습니다.

**Comment by luceinaltis** [comment]
1. 모듈 선언 부분
2. ..?
3. 전역 변수의 충돌 방지

**Comment by chap95** [comment]
3주차 종료
